### ISSUE TITLE
Does this support sharded Mongo Databases?

### ISSUE THREAD

**Issue by pdubb29** [AppSpaceIT/MongoDbCache#5]

**Comment by petrhaus** [comment]
I haven't tested it, but it should work.
The primary key (_id) is the cache key and is the only candidate for the shard key. Also, all the operational requirements should be met.
Please, tell me if you are able to test it, otherwise I'll try to get an access to a sharded cluster and do some testing.

**Comment by pdubb29** [comment]
I guess I misunderstood how we were implementing the database.  So it's not being sharded, but using a replica set. When I test putting items in the cache and pulling them out on a local database, it seems to work just fine. 
But then when I'm using a different environment with one replica set, it's not getting the appropriate value out of the cache. I was wondering if this might be related. 
I'm going to be putting some more logging statements in and seeing what results we're getting out of the distributed cache collection.

Thanks for your quick response!

**Comment by petrhaus** [comment]
In case of a replica set you should pay attention to the read preference mode, which should be _primary_ (the default).
Let me know how it goes :-)

**Comment by pdubb29** [comment]
Turns out this works perfectly fine. Some other piece of the application was causing it to have an invalid value. 

Logging FTW!
